### ISSUE TITLE
set zephyr-network-info revision to v1.2.1

### ISSUE THREAD

**Issue by rajeev1986** [golioth/zephyr-network-info#15]
Please update the revision to **v1.2.1** in the [readme](https://github.com/golioth/zephyr-network-info?tab=readme-ov-file#using-this-library) else the library fails to compile on the newer nRF Connect SDK v2.9.0.

```
projects:
  - name: zephyr-network-info
    path: modules/lib/network-info
    revision: v1.2.1
    url: https://github.com/golioth/zephyr-network-info
```

Thanks
